import { CalendarMonth } from 'src/models/calendar-month.model';
import { DayActivityType } from 'src/models/day-activity-type.model';
import { DayMomentumType } from 'src/models/day-momentum-type.model copy';
import { CalendarMonthIncomeReport } from 'src/models/income-report/calendar-month-income-report.model';
import { createCalendarMonthIncomeReport } from './create-calendar-month-income-report';

describe('Create-Calendar-Month-Income-Report', () => {
  const calendarMonth: CalendarMonth = {
    longMonthName: 'январь',
    shortMonthName: 'янв.',
    daysInMonth: 31,
    calendarDays: [
      {
        dayNameShort: 'пн',
        dayNameLong: 'понедельник',
        dayNumberStr: '30',
        dayNumber: 30,
        dayOfWeek: 1,
        dayDateStr: '30 дек. 2019',
        dayActivityType: DayActivityType.NOT_DEFINED,
        dayMomentumType: DayMomentumType.BEFORE,
        dayCSS: 'day-before',
        dayIncomes: [],
        monthNumber: 1,
      },
      {
        dayNameShort: 'вт',
        dayNameLong: 'вторник',
        dayNumberStr: '31',
        dayNumber: 31,
        dayOfWeek: 2,
        dayDateStr: '31 дек. 2019',
        dayActivityType: DayActivityType.NOT_DEFINED,
        dayMomentumType: DayMomentumType.BEFORE,
        dayCSS: 'day-before',
        dayIncomes: [],
        monthNumber: 1,
      },
      {
        dayNameShort: 'ср',
        dayNameLong: 'среда',
        dayNumber: 1,
        dayNumberStr: '01',
        dayDateStr: '01 янв. 2020',
        dayOfWeek: 3,
        dayActivityType: DayActivityType.NOT_DEFINED,
        dayMomentumType: DayMomentumType.CURRENT,
        dayCSS: 'day-current',
        monthNumber: 1,
        dayIncomes: [
          {
            id: 'number1',
            dayDateStr: '01 января 2020',
            dayCSS: 'day-working',
            docNumber: '',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
          },
          {
            id: 'number11',
            dayDateStr: '01 января 2020',
            dayCSS: 'day-working',
            docNumber: '33',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
          },
          {
            id: 'number12',
            dayDateStr: '01 января 2020',
            dayCSS: 'day-working',
            docNumber: '443',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
          },
        ],
      },
      {
        dayNameShort: 'чт',
        dayNameLong: 'четверг',
        dayNumber: 2,
        dayNumberStr: '02',
        dayDateStr: '02 янв. 2020',
        dayOfWeek: 4,
        dayActivityType: DayActivityType.NOT_DEFINED,
        dayMomentumType: DayMomentumType.CURRENT,
        dayCSS: 'day-current',
        monthNumber: 1,
        dayIncomes: [
          {
            id: 'number2',
            docNumber: '',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '02 янв. 2020',
            dayCSS: 'day-current',
          },
          {
            id: 'number21',
            docNumber: '00000000001235',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '02 янв. 2020',
            dayCSS: 'day-current',
          },
          {
            id: 'number22',
            docNumber: '00000000001234',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '02 янв. 2020',
            dayCSS: 'day-current',
          },
        ],
      },
      {
        dayNameShort: 'пт',
        dayNameLong: 'пятница',
        dayNumber: 3,
        dayNumberStr: '03',
        dayDateStr: '03 янв. 2020',
        dayOfWeek: 5,
        dayActivityType: DayActivityType.NOT_DEFINED,
        dayMomentumType: DayMomentumType.CURRENT,
        dayCSS: 'day-current',
        monthNumber: 1,
        dayIncomes: [
          {
            id: 'number3',
            docNumber: '',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '03 янв. 2020',
            dayCSS: 'day-current',
          },
          {
            id: 'number31',
            docNumber: '00000000001235',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '03 янв. 2020',
            dayCSS: 'day-current',
          },
          {
            id: 'number32',
            docNumber: '00000000001234',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '03 янв. 2020',
            dayCSS: 'day-current',
          },
        ],
      },
      {
        dayNameShort: 'сб',
        dayNameLong: 'суббота',
        dayNumber: 4,
        dayNumberStr: '04',
        dayDateStr: '04 янв. 2020',
        dayOfWeek: 6,
        dayActivityType: DayActivityType.NOT_DEFINED,
        dayMomentumType: DayMomentumType.CURRENT,
        dayCSS: 'day-current',
        monthNumber: 1,
        dayIncomes: [
          {
            id: 'number4',
            docNumber: '',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '04 янв. 2020',
            dayCSS: 'day-current',
          },
          {
            id: 'number41',
            docNumber: '00000000001235',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '04 янв. 2020',
            dayCSS: 'day-current',
          },
          {
            id: 'number42',
            docNumber: '00000000001234',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '04 янв. 2020',
            dayCSS: 'day-current',
          },
        ],
      },
      {
        dayNameShort: 'вс',
        dayNameLong: 'воскресенье',
        dayNumber: 5,
        dayNumberStr: '05',
        dayDateStr: '05 янв. 2020',
        dayOfWeek: 7,
        dayActivityType: DayActivityType.NOT_DEFINED,
        dayMomentumType: DayMomentumType.CURRENT,
        dayCSS: 'day-current',
        monthNumber: 1,
        dayIncomes: [
          {
            id: 'number5',
            docNumber: '',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '05 янв. 2020',
            dayCSS: 'day-current',
          },
          {
            id: 'number51',
            docNumber: '00000000001235',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '05 янв. 2020',
            dayCSS: 'day-current',
          },
          {
            id: 'number52',
            docNumber: '00000000001234',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '05 янв. 2020',
            dayCSS: 'day-current',
          },
        ],
      },
      {
        dayNameShort: 'пн',
        dayNameLong: 'понедельник',
        dayNumber: 6,
        dayNumberStr: '06',
        dayDateStr: '06 янв. 2020',
        dayOfWeek: 1,
        dayActivityType: DayActivityType.NOT_DEFINED,
        dayMomentumType: DayMomentumType.CURRENT,
        dayCSS: 'day-current',
        monthNumber: 1,
        dayIncomes: [
          {
            id: 'number6',
            docNumber: '',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '06 янв. 2020',
            dayCSS: 'day-current',
          },
          {
            id: 'number61',
            docNumber: '00000000001235',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '06 янв. 2020',
            dayCSS: 'day-current',
          },
          {
            id: 'number62',
            docNumber: '00000000001234',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '06 янв. 2020',
            dayCSS: 'day-current',
          },
        ],
      },
      {
        dayNameShort: 'вт',
        dayNameLong: 'вторник',
        dayNumber: 7,
        dayNumberStr: '07',
        dayDateStr: '07 янв. 2020',
        dayOfWeek: 2,
        dayActivityType: DayActivityType.NOT_DEFINED,
        dayMomentumType: DayMomentumType.CURRENT,
        dayCSS: 'day-current',
        monthNumber: 1,
        dayIncomes: [
          {
            id: 'number7',
            docNumber: '',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '07 янв. 2020',
            dayCSS: 'day-current',
          },
          {
            id: 'number71',
            docNumber: '00000000001235',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '07 янв. 2020',
            dayCSS: 'day-current',
          },
          {
            id: 'number72',
            docNumber: '00000000001234',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '07 янв. 2020',
            dayCSS: 'day-current',
          },
        ],
      },
      {
        dayNameShort: 'ср',
        dayNameLong: 'среда',
        dayNumber: 8,
        dayNumberStr: '08',
        dayDateStr: '08 янв. 2020',
        dayOfWeek: 3,
        dayActivityType: DayActivityType.NOT_DEFINED,
        dayMomentumType: DayMomentumType.CURRENT,
        dayCSS: 'day-current',
        monthNumber: 1,
        dayIncomes: [
          {
            id: 'number8',
            docNumber: '',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '08 янв. 2020',
            dayCSS: 'day-current',
          },
          {
            id: 'number81',
            docNumber: '00000000001235',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '08 янв. 2020',
            dayCSS: 'day-current',
          },
          {
            id: 'number82',
            docNumber: '00000000001234',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '08 янв. 2020',
            dayCSS: 'day-current',
          },
        ],
      },
      {
        dayNameShort: 'чт',
        dayNameLong: 'четверг',
        dayNumber: 9,
        dayNumberStr: '09',
        dayDateStr: '09 янв. 2020',
        dayOfWeek: 4,
        dayActivityType: DayActivityType.NOT_DEFINED,
        dayMomentumType: DayMomentumType.CURRENT,
        dayCSS: 'day-current',
        monthNumber: 1,
        dayIncomes: [
          {
            id: 'number9',
            docNumber: '',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '09 янв. 2020',
            dayCSS: 'day-current',
          },
          {
            id: 'number91',
            docNumber: '00000000001235',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '09 янв. 2020',
            dayCSS: 'day-current',
          },
          {
            id: 'number92',
            docNumber: '00000000001234',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '09 янв. 2020',
            dayCSS: 'day-current',
          },
        ],
      },
      {
        dayNameShort: 'пт',
        dayNameLong: 'пятница',
        dayNumber: 10,
        dayNumberStr: '10',
        dayDateStr: '10 янв. 2020',
        dayOfWeek: 5,
        dayActivityType: DayActivityType.NOT_DEFINED,
        dayMomentumType: DayMomentumType.CURRENT,
        dayCSS: 'day-current',
        monthNumber: 1,
        dayIncomes: [
          {
            id: 'number10',
            docNumber: '',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '10 янв. 2020',
            dayCSS: 'day-current',
          },
          {
            id: 'number101',
            docNumber: '00000000001235',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '10 янв. 2020',
            dayCSS: 'day-current',
          },
          {
            id: 'number102',
            docNumber: '00000000001234',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '10 янв. 2020',
            dayCSS: 'day-current',
          },
        ],
      },
      {
        dayNameShort: 'сб',
        dayNameLong: 'суббота',
        dayNumber: 11,
        dayNumberStr: '11',
        dayDateStr: '11 янв. 2020',
        dayOfWeek: 6,
        dayActivityType: DayActivityType.NOT_DEFINED,
        dayMomentumType: DayMomentumType.CURRENT,
        dayCSS: 'day-current',
        monthNumber: 1,
        dayIncomes: [
          {
            id: 'number11',
            docNumber: '',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '11 янв. 2020',
            dayCSS: 'day-current',
          },
          {
            id: 'number111',
            docNumber: '00000000001235',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '11 янв. 2020',
            dayCSS: 'day-current',
          },
          {
            id: 'number112',
            docNumber: '00000000001234',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '11 янв. 2020',
            dayCSS: 'day-current',
          },
        ],
      },
      {
        dayNameShort: 'вс',
        dayNameLong: 'воскресенье',
        dayNumber: 12,
        dayNumberStr: '12',
        dayDateStr: '12 янв. 2020',
        dayOfWeek: 7,
        dayActivityType: DayActivityType.NOT_DEFINED,
        dayMomentumType: DayMomentumType.CURRENT,
        dayCSS: 'day-current',
        monthNumber: 1,
        dayIncomes: [
          {
            id: 'number12',
            docNumber: '',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '12 янв. 2020',
            dayCSS: 'day-current',
          },
          {
            id: 'number121',
            docNumber: '00000000001235',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '12 янв. 2020',
            dayCSS: 'day-current',
          },
          {
            id: 'number122',
            docNumber: '00000000001234',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '12 янв. 2020',
            dayCSS: 'day-current',
          },
        ],
      },
      {
        dayNameShort: 'пн',
        dayNameLong: 'понедельник',
        dayNumber: 13,
        dayNumberStr: '13',
        dayDateStr: '13 янв. 2020',
        dayOfWeek: 1,
        dayActivityType: DayActivityType.NOT_DEFINED,
        dayMomentumType: DayMomentumType.CURRENT,
        dayCSS: 'day-current',
        monthNumber: 1,
        dayIncomes: [
          {
            id: 'number13',
            docNumber: '',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '13 янв. 2020',
            dayCSS: 'day-current',
          },
          {
            id: 'number131',
            docNumber: '00000000001235',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '13 янв. 2020',
            dayCSS: 'day-current',
          },
          {
            id: 'number132',
            docNumber: '00000000001234',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '13 янв. 2020',
            dayCSS: 'day-current',
          },
        ],
      },
      {
        dayNameShort: 'вт',
        dayNameLong: 'вторник',
        dayNumber: 14,
        dayNumberStr: '14',
        dayDateStr: '14 янв. 2020',
        dayOfWeek: 2,
        dayActivityType: DayActivityType.NOT_DEFINED,
        dayMomentumType: DayMomentumType.CURRENT,
        dayCSS: 'day-current',
        monthNumber: 1,
        dayIncomes: [
          {
            id: 'number14',
            docNumber: '',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '14 янв. 2020',
            dayCSS: 'day-current',
          },
          {
            id: 'number141',
            docNumber: '00000000001235',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '14 янв. 2020',
            dayCSS: 'day-current',
          },
          {
            id: 'number142',
            docNumber: '00000000001234',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '14 янв. 2020',
            dayCSS: 'day-current',
          },
        ],
      },
      {
        dayNameShort: 'ср',
        dayNameLong: 'среда',
        dayNumber: 15,
        dayNumberStr: '15',
        dayDateStr: '15 янв. 2020',
        dayOfWeek: 3,
        dayActivityType: DayActivityType.NOT_DEFINED,
        dayMomentumType: DayMomentumType.CURRENT,
        dayCSS: 'day-current',
        monthNumber: 1,
        dayIncomes: [
          {
            id: 'number15',
            docNumber: '',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '15 янв. 2020',
            dayCSS: 'day-current',
          },
          {
            id: 'number151',
            docNumber: '00000000001235',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '15 янв. 2020',
            dayCSS: 'day-current',
          },
          {
            id: 'number152',
            docNumber: '00000000001234',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '15 янв. 2020',
            dayCSS: 'day-current',
          },
        ],
      },
      {
        dayNameShort: 'чт',
        dayNameLong: 'четверг',
        dayNumber: 16,
        dayNumberStr: '16',
        dayDateStr: '16 янв. 2020',
        dayOfWeek: 4,
        dayActivityType: DayActivityType.NOT_DEFINED,
        dayMomentumType: DayMomentumType.CURRENT,
        dayCSS: 'day-current',
        monthNumber: 1,
        dayIncomes: [
          {
            id: 'number16',
            docNumber: '',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '16 янв. 2020',
            dayCSS: 'day-current',
          },
          {
            id: 'number161',
            docNumber: '00000000001235',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '16 янв. 2020',
            dayCSS: 'day-current',
          },
          {
            id: 'number162',
            docNumber: '00000000001234',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '16 янв. 2020',
            dayCSS: 'day-current',
          },
        ],
      },
      {
        dayNameShort: 'пт',
        dayNameLong: 'пятница',
        dayNumber: 17,
        dayNumberStr: '17',
        dayDateStr: '17 янв. 2020',
        dayOfWeek: 5,
        dayActivityType: DayActivityType.NOT_DEFINED,
        dayMomentumType: DayMomentumType.CURRENT,
        dayCSS: 'day-current',
        monthNumber: 1,
        dayIncomes: [
          {
            id: 'number17',
            docNumber: '',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '17 янв. 2020',
            dayCSS: 'day-current',
          },
          {
            id: 'number171',
            docNumber: '00000000001235',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '17 янв. 2020',
            dayCSS: 'day-current',
          },
          {
            id: 'number172',
            docNumber: '00000000001234',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '17 янв. 2020',
            dayCSS: 'day-current',
          },
        ],
      },
      {
        dayNameShort: 'сб',
        dayNameLong: 'суббота',
        dayNumber: 18,
        dayNumberStr: '18',
        dayDateStr: '18 янв. 2020',
        dayOfWeek: 6,
        dayActivityType: DayActivityType.NOT_DEFINED,
        dayMomentumType: DayMomentumType.CURRENT,
        dayCSS: 'day-current',
        monthNumber: 1,
        dayIncomes: [
          {
            id: 'number18',
            docNumber: '',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '18 янв. 2020',
            dayCSS: 'day-current',
          },
          {
            id: 'number181',
            docNumber: '00000000001235',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '18 янв. 2020',
            dayCSS: 'day-current',
          },
          {
            id: 'number182',
            docNumber: '00000000001234',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '18 янв. 2020',
            dayCSS: 'day-current',
          },
        ],
      },
      {
        dayNameShort: 'вс',
        dayNameLong: 'воскресенье',
        dayNumber: 19,
        dayNumberStr: '19',
        dayDateStr: '19 янв. 2020',
        dayOfWeek: 7,
        dayActivityType: DayActivityType.NOT_DEFINED,
        dayMomentumType: DayMomentumType.CURRENT,
        dayCSS: 'day-current',
        monthNumber: 1,
        dayIncomes: [
          {
            id: 'number19',
            docNumber: '',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '19 янв. 2020',
            dayCSS: 'day-current',
          },
          {
            id: 'number191',
            docNumber: '00000000001235',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '19 янв. 2020',
            dayCSS: 'day-current',
          },
          {
            id: 'number192',
            docNumber: '00000000001234',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '19 янв. 2020',
            dayCSS: 'day-current',
          },
        ],
      },
      {
        dayNameShort: 'пн',
        dayNameLong: 'понедельник',
        dayNumber: 20,
        dayNumberStr: '20',
        dayDateStr: '20 янв. 2020',
        dayOfWeek: 1,
        dayActivityType: DayActivityType.NOT_DEFINED,
        dayMomentumType: DayMomentumType.CURRENT,
        dayCSS: 'day-current',
        monthNumber: 1,
        dayIncomes: [
          {
            id: 'number20',
            docNumber: '',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '20 янв. 2020',
            dayCSS: 'day-current',
          },
          {
            id: 'number201',
            docNumber: '00000000001235',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '20 янв. 2020',
            dayCSS: 'day-current',
          },
          {
            id: 'number202',
            docNumber: '00000000001234',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '20 янв. 2020',
            dayCSS: 'day-current',
          },
        ],
      },
      {
        dayNameShort: 'вт',
        dayNameLong: 'вторник',
        dayNumber: 21,
        dayNumberStr: '21',
        dayDateStr: '21 янв. 2020',
        dayOfWeek: 2,
        dayActivityType: DayActivityType.NOT_DEFINED,
        dayMomentumType: DayMomentumType.CURRENT,
        dayCSS: 'day-current',
        monthNumber: 1,
        dayIncomes: [
          {
            id: 'number21',
            docNumber: '',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '21 янв. 2020',
            dayCSS: 'day-current',
          },
          {
            id: 'number211',
            docNumber: '00000000001235',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '21 янв. 2020',
            dayCSS: 'day-current',
          },
          {
            id: 'number212',
            docNumber: '00000000001234',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '21 янв. 2020',
            dayCSS: 'day-current',
          },
        ],
      },
      {
        dayNameShort: 'ср',
        dayNameLong: 'среда',
        dayNumber: 22,
        dayNumberStr: '22',
        dayDateStr: '22 янв. 2020',
        dayOfWeek: 3,
        dayActivityType: DayActivityType.NOT_DEFINED,
        dayMomentumType: DayMomentumType.CURRENT,
        dayCSS: 'day-current',
        monthNumber: 1,
        dayIncomes: [
          {
            id: 'number22',
            docNumber: '',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '22 янв. 2020',
            dayCSS: 'day-current',
          },
          {
            id: 'number221',
            docNumber: '00000000001235',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '22 янв. 2020',
            dayCSS: 'day-current',
          },
          {
            id: 'number222',
            docNumber: '00000000001234',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '22 янв. 2020',
            dayCSS: 'day-current',
          },
        ],
      },
      {
        dayNameShort: 'чт',
        dayNameLong: 'четверг',
        dayNumber: 23,
        dayNumberStr: '23',
        dayDateStr: '23 янв. 2020',
        dayOfWeek: 4,
        dayActivityType: DayActivityType.NOT_DEFINED,
        dayMomentumType: DayMomentumType.CURRENT,
        dayCSS: 'day-current',
        monthNumber: 1,
        dayIncomes: [
          {
            id: 'number23',
            docNumber: '',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '23 янв. 2020',
            dayCSS: 'day-current',
          },
          {
            id: 'number231',
            docNumber: '00000000001235',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '23 янв. 2020',
            dayCSS: 'day-current',
          },
          {
            id: 'number232',
            docNumber: '00000000001234',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '23 янв. 2020',
            dayCSS: 'day-current',
          },
        ],
      },
      {
        dayNameShort: 'пт',
        dayNameLong: 'пятница',
        dayNumber: 24,
        dayNumberStr: '24',
        dayDateStr: '24 янв. 2020',
        dayOfWeek: 5,
        dayActivityType: DayActivityType.NOT_DEFINED,
        dayMomentumType: DayMomentumType.CURRENT,
        dayCSS: 'day-current',
        monthNumber: 1,
        dayIncomes: [
          {
            id: 'number24',
            docNumber: '',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '24 янв. 2020',
            dayCSS: 'day-current',
          },
          {
            id: 'number241',
            docNumber: '00000000001235',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '24 янв. 2020',
            dayCSS: 'day-current',
          },
          {
            id: 'number242',
            docNumber: '00000000001234',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '24 янв. 2020',
            dayCSS: 'day-current',
          },
        ],
      },
      {
        dayNameShort: 'сб',
        dayNameLong: 'суббота',
        dayNumber: 25,
        dayNumberStr: '25',
        dayDateStr: '25 янв. 2020',
        dayOfWeek: 6,
        dayActivityType: DayActivityType.NOT_DEFINED,
        dayMomentumType: DayMomentumType.CURRENT,
        dayCSS: 'day-current',
        monthNumber: 1,
        dayIncomes: [
          {
            id: 'number25',
            docNumber: '',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '25 янв. 2020',
            dayCSS: 'day-current',
          },
          {
            id: 'number251',
            docNumber: '00000000001235',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '25 янв. 2020',
            dayCSS: 'day-current',
          },
          {
            id: 'number252',
            docNumber: '00000000001234',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '25 янв. 2020',
            dayCSS: 'day-current',
          },
        ],
      },
      {
        dayNameShort: 'вс',
        dayNameLong: 'воскресенье',
        dayNumber: 26,
        dayNumberStr: '26',
        dayDateStr: '26 янв. 2020',
        dayOfWeek: 7,
        dayActivityType: DayActivityType.NOT_DEFINED,
        dayMomentumType: DayMomentumType.CURRENT,
        dayCSS: 'day-current',
        monthNumber: 1,
        dayIncomes: [
          {
            id: 'number26',
            docNumber: '',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '26 янв. 2020',
            dayCSS: 'day-current',
          },
          {
            id: 'number261',
            docNumber: '00000000001235',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '26 янв. 2020',
            dayCSS: 'day-current',
          },
          {
            id: 'number262',
            docNumber: '00000000001234',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '26 янв. 2020',
            dayCSS: 'day-current',
          },
        ],
      },
      {
        dayNameShort: 'пн',
        dayNameLong: 'понедельник',
        dayNumber: 27,
        dayNumberStr: '27',
        dayDateStr: '27 янв. 2020',
        dayOfWeek: 1,
        dayActivityType: DayActivityType.NOT_DEFINED,
        dayMomentumType: DayMomentumType.CURRENT,
        dayCSS: 'day-current',
        monthNumber: 1,
        dayIncomes: [
          {
            id: 'number27',
            docNumber: '',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '27 янв. 2020',
            dayCSS: 'day-current',
          },
          {
            id: 'number271',
            docNumber: '00000000001235',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '27 янв. 2020',
            dayCSS: 'day-current',
          },
          {
            id: 'number272',
            docNumber: '00000000001234',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '27 янв. 2020',
            dayCSS: 'day-current',
          },
        ],
      },
      {
        dayNameShort: 'вт',
        dayNameLong: 'вторник',
        dayNumber: 28,
        dayNumberStr: '28',
        dayDateStr: '28 янв. 2020',
        dayOfWeek: 2,
        dayActivityType: DayActivityType.NOT_DEFINED,
        dayMomentumType: DayMomentumType.CURRENT,
        dayCSS: 'day-current',
        monthNumber: 1,
        dayIncomes: [
          {
            id: 'number28',
            docNumber: '',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '28 янв. 2020',
            dayCSS: 'day-current',
          },
          {
            id: 'number281',
            docNumber: '00000000001235',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '28 янв. 2020',
            dayCSS: 'day-current',
          },
          {
            id: 'number282',
            docNumber: '00000000001234',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '28 янв. 2020',
            dayCSS: 'day-current',
          },
        ],
      },
      {
        dayNameShort: 'ср',
        dayNameLong: 'среда',
        dayNumber: 29,
        dayNumberStr: '29',
        dayDateStr: '29 янв. 2020',
        dayOfWeek: 3,
        dayActivityType: DayActivityType.NOT_DEFINED,
        dayMomentumType: DayMomentumType.CURRENT,
        dayCSS: 'day-current',
        monthNumber: 1,
        dayIncomes: [
          {
            id: 'number29',
            docNumber: '',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '29 янв. 2020',
            dayCSS: 'day-current',
          },
          {
            id: 'number291',
            docNumber: '00000000001235',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '29 янв. 2020',
            dayCSS: 'day-current',
          },
          {
            id: 'number292',
            docNumber: '00000000001234',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '29 янв. 2020',
            dayCSS: 'day-current',
          },
        ],
      },
      {
        dayNameShort: 'чт',
        dayNameLong: 'четверг',
        dayNumber: 30,
        dayNumberStr: '30',
        dayDateStr: '30 янв. 2020',
        dayOfWeek: 4,
        dayActivityType: DayActivityType.NOT_DEFINED,
        dayMomentumType: DayMomentumType.CURRENT,
        dayCSS: 'day-current',
        monthNumber: 1,
        dayIncomes: [
          {
            id: 'number30',
            docNumber: '',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '30 янв. 2020',
            dayCSS: 'day-current',
          },
          {
            id: 'number301',
            docNumber: '00000000001235',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '30 янв. 2020',
            dayCSS: 'day-current',
          },
          {
            id: 'number302',
            docNumber: '00000000001234',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '30 янв. 2020',
            dayCSS: 'day-current',
          },
        ],
      },
      {
        dayNameShort: 'пт',
        dayNameLong: 'пятница',
        dayNumber: 31,
        dayNumberStr: '31',
        dayDateStr: '31 янв. 2020',
        dayOfWeek: 5,
        dayActivityType: DayActivityType.NOT_DEFINED,
        dayMomentumType: DayMomentumType.CURRENT,
        dayCSS: 'day-current',
        monthNumber: 1,
        dayIncomes: [
          {
            id: 'number31',
            docNumber: '',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '31 янв. 2020',
            dayCSS: 'day-current',
          },
          {
            id: 'number311',
            docNumber: '00000000001235',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '31 янв. 2020',
            dayCSS: 'day-current',
          },
          {
            id: 'number312',
            docNumber: '00000000001234',
            incomeSum: 20000,
            incomeTypeName: 'наличные',
            dayDateStr: '31 янв. 2020',
            dayCSS: 'day-current',
          },
        ],
      },
      {
        dayNameShort: 'сб',
        dayNameLong: 'суббота',
        dayNumberStr: '01',
        dayNumber: 1,
        dayOfWeek: 6,
        dayActivityType: DayActivityType.NOT_DEFINED,
        dayDateStr: '01 февр. 2020',
        dayMomentumType: DayMomentumType.AFTER,
        dayCSS: 'day-after',
        monthNumber: 1,
        dayIncomes: [],
      },
      {
        dayNameShort: 'вс',
        dayNameLong: 'воскресенье',
        dayNumberStr: '02',
        dayNumber: 2,
        dayOfWeek: 7,
        dayActivityType: DayActivityType.NOT_DEFINED,
        dayDateStr: '02 февр. 2020',
        dayMomentumType: DayMomentumType.AFTER,
        dayCSS: 'day-after',
        monthNumber: 1,
        dayIncomes: [],
      },
    ],
    monthNumber: 1,
    monthNumberStr: '01',
    monthSettings: {
      longMonthName: 'январь',
      income: 300,
      pensionTax: 29,
      socialTax: 6,
    },
  };
  beforeEach(() => {});
  it('should correctly summarize months incomes ', () => {
    const monthIncomeReport: CalendarMonthIncomeReport = createCalendarMonthIncomeReport(
      calendarMonth
    );

    expect(monthIncomeReport.longMonthName).toEqual('январь');
    expect(monthIncomeReport.shortMonthName).toEqual('янв.');
    expect(monthIncomeReport.monthNumberStr).toEqual('01');
    expect(monthIncomeReport.daysInMonth).toEqual(31);
    expect(monthIncomeReport.monthNumber).toEqual(1);
    expect(monthIncomeReport.daysIncomeRecords.length).toEqual(35);
    expect(monthIncomeReport.monthIncomeTotal).toEqual(60000 * 31);
  });
});
